---
- name: Install Java
  yum: name=java-1.8.0-openjdk-headless state=present

- name: Enable elasticsearch repo
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  yum: name=elasticsearch state=present

- name: Install elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch

- name: Start elasticsearch
  service: name=elasticsearch state=started enabled=yes
