########################################################################
# Universal role which installs and configures an elasticsearch node.
#
# Supported vars:
# - es_interface_name (default: lo) - elastic shall bind to this iface
# - es_cluster_name (default: elastic)
# - es_multicast (default: false)
# - es_unicast_hosts (default: []) - list of other es hosts in cluster
# - es_http_port (default: 9200-9299)
# - es_transport_port (default: 9300-9400)
# - es_nodes_group (default: false) - name of the ansible group which holds all hosts in this cluster
# - es_allowed_ips (passed to open-port)
# - es_allowed_group (passed to open-port)
########################################################################
---
- name: Install Java
  yum: name=java-1.8.0-openjdk-headless state=present

- name: Enable elasticsearch repo
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  yum: name=elasticsearch state=present

- name: Install elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch

- name: Start elasticsearch
  service: name=elasticsearch state=started enabled=yes
